Phage name: 14-1
fasta file: input/genome_data/14-1.fasta
enriched fastq: input/fastq_data/phage_14-1_enriched.fastq
control fastq: input/fastq_data/phage_14-1_control.fastq
ID: pooled
termseq alpha: 0.001

cluster width:
  TSS: 10
  TTS: 20

minimum coverage: 
  enriched:
    TSS: 5
    TTS: 30
  control:
    TSS: 2
    TTS: 2
    
peak alignment error: 2
TSS Threshold: 1
TTS threshold: 0.20

TSS sequence extraction:
  upstream: 50
  downstream: 10

TTS sequence extraction:
  upstream: 30
  downstream: 30

#MEME params
nmotifsTSS: 5
nmotifsTTS: 4