Phage name: LUZ19
fasta file: PAO1.fasta
enriched fastq: LUZ7_enriched.fastq
control fastq: LUZ7_control.fastq
ID: pooledPAO1
termseq alpha: 0.001

cluster width:
  TSS: 10
  TTS: 20

minimum coverage: 
  enriched:
    TSS: 5
    TTS: 30
  control:
    TSS: 2
    TTS: 2
    

peak alignment error: 2
TSS Threshold: 2
TTS threshold: 0.20

TSS sequence extraction:
  upstream: 50
  downstream: 10

TTS sequence extraction:
  upstream: 30
  downstream: 30

#MEME params
nmotifsTSS: 3
nmotifsTTS: 3